name: 'Local Cache'
description: 'Faster caching action that uses our local cache on Inova'
inputs:
  folder:
    description: 'Folder to cache'
    required: true
  key:
    description: 'Cache key'
    required: true
  save:
    description: 'true/false whether to save cache after workflow is done'
    default: "true"
  restore:
    description: 'true/false whether to restore cache before continuing with the workflow'
    default: "true"
runs:
  using: "composite"
  steps:
    - uses: inovait/action-localcache/internal@b0d74a1cffd0929edbe41c11c6662f9d56cdadf8
      with:
        folder: '${{ inputs.folder }}'
        key: '${{ inputs.key }}'
        save: '${{ inputs.save }}'
        restore: '${{ inputs.restore }}'
        repo: '${{ github.repository }}'
        token: '${{ github.token }}'
