name: 'Local Cache'
description: 'Faster caching action that uses our local cache on Inova'
inputs:
  folder:
    description: 'Folder to cache'
    required: true
  key:
    description: 'Cache key'
    required: true
  save:
    description: 'true/false whether to save cache after workflow is done'
    default: "true"
  restore:
    description: 'true/false whether to restore cache before continuing with the workflow'
    default: "true"
runs:
  using: 'node16'
  main: 'dist/index.js' 
  post: 'dist-post/index.js'
  post-if: success()
